// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwHpV1V_aAnjITEdbj7WcA9-81f7ROPA',
    appId: '1:1022934926661:web:c33d42ecf203a0b14aaa2c',
    messagingSenderId: '1022934926661',
    projectId: 'ecommerce-a95ab',
    authDomain: 'ecommerce-a95ab.firebaseapp.com',
    storageBucket: 'ecommerce-a95ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeRA7Jvx7vK6HZ8FXN8jNM2KeatF68oUw',
    appId: '1:1022934926661:android:a90be2b41da744694aaa2c',
    messagingSenderId: '1022934926661',
    projectId: 'ecommerce-a95ab',
    storageBucket: 'ecommerce-a95ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHVg7A8dcDiqTVr4lP2S_RHKaZz0Tq9mQ',
    appId: '1:1022934926661:ios:5be502f30dd543414aaa2c',
    messagingSenderId: '1022934926661',
    projectId: 'ecommerce-a95ab',
    storageBucket: 'ecommerce-a95ab.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHVg7A8dcDiqTVr4lP2S_RHKaZz0Tq9mQ',
    appId: '1:1022934926661:ios:5be502f30dd543414aaa2c',
    messagingSenderId: '1022934926661',
    projectId: 'ecommerce-a95ab',
    storageBucket: 'ecommerce-a95ab.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOwHpV1V_aAnjITEdbj7WcA9-81f7ROPA',
    appId: '1:1022934926661:web:881c10ce058553f84aaa2c',
    messagingSenderId: '1022934926661',
    projectId: 'ecommerce-a95ab',
    authDomain: 'ecommerce-a95ab.firebaseapp.com',
    storageBucket: 'ecommerce-a95ab.appspot.com',
  );
}
